
package webserver.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MazeRunnerImplService", targetNamespace = "http://ws.node.mazerunner.com/", wsdlLocation = "http://localhost:8888/MazeRunnerNodeWS?wsdl")
public class MazeRunnerImplService
    extends Service
{

    private final static URL MAZERUNNERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAZERUNNERIMPLSERVICE_EXCEPTION;
    private final static QName MAZERUNNERIMPLSERVICE_QNAME = new QName("http://ws.node.mazerunner.com/", "MazeRunnerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/MazeRunnerNodeWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAZERUNNERIMPLSERVICE_WSDL_LOCATION = url;
        MAZERUNNERIMPLSERVICE_EXCEPTION = e;
    }

    public MazeRunnerImplService() {
        super(__getWsdlLocation(), MAZERUNNERIMPLSERVICE_QNAME);
    }

    public MazeRunnerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAZERUNNERIMPLSERVICE_QNAME, features);
    }

    public MazeRunnerImplService(URL wsdlLocation) {
        super(wsdlLocation, MAZERUNNERIMPLSERVICE_QNAME);
    }

    public MazeRunnerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAZERUNNERIMPLSERVICE_QNAME, features);
    }

    public MazeRunnerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MazeRunnerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MazeRunnerService
     */
    @WebEndpoint(name = "MazeRunnerImplPort")
    public MazeRunnerService getMazeRunnerImplPort() {
        return super.getPort(new QName("http://ws.node.mazerunner.com/", "MazeRunnerImplPort"), MazeRunnerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MazeRunnerService
     */
    @WebEndpoint(name = "MazeRunnerImplPort")
    public MazeRunnerService getMazeRunnerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.node.mazerunner.com/", "MazeRunnerImplPort"), MazeRunnerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAZERUNNERIMPLSERVICE_EXCEPTION!= null) {
            throw MAZERUNNERIMPLSERVICE_EXCEPTION;
        }
        return MAZERUNNERIMPLSERVICE_WSDL_LOCATION;
    }

}
